dist: xenial
language: cpp
sudo: required
branches:
  only:
    - master
    - cleaner_parsing
    - scaling-old-parsing
    - batch_parsing
    - batch_parsing_output
    - blocked_input
    - bug_fixes
matrix:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      env:
        # Set POPCNT_CAPABILITY=0 to avoid build error
        - POPCNT_CAPABILITY=0
        - NO_TBB=1
      script: travis_wait 30 make -j $NPROC allall
    # ARM 64-bit
    - os: linux
      arch: arm64
      compiler: gcc
      env:
        # Set POPCNT_CAPABILITY=0 to avoid build error
        - POPCNT_CAPABILITY=0
        - NO_TBB=1
      script: travis_wait 30 make -j $NPROC allall

cache: apt
env:
  global:
    - NPROC="$(nproc)"
before_script:
  - uname -m
  - python3 --version
  - echo CC=${CC} CXX=${CXX} NPROC=${NPROC}
  - $CC --version
  - $CXX --version
script: make -j $NPROC allall && make simple-test
notifications:
  slack:
    secure: tfzT8N1fNV+oSV7tide9WrAj3ifs+LONJ3fCH1tUzexqrx23te4lE0oAj9C1cEMJ4evyRYwHNG8HZoLCOy8EfapqbWm6vgLIlkIBpeZ9E6f2jG6v0YuVDWWpqQC3qdGXCqWtHPjgs3i5OLsLwwQ/LItLoTqpBk2aYv+vGNs2F9g=
